"""Stable model-gateway enums shared by providers, traces, and APIs."""

from enum import StrEnum


class ModelErrorCode(StrEnum):
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_CONNECTION_ERROR = "MODEL_CONNECTION_ERROR"
    MODEL_RATE_LIMITED = "MODEL_RATE_LIMITED"
    MODEL_SERVER_ERROR = "MODEL_SERVER_ERROR"
    MODEL_AUTHENTICATION_ERROR = "MODEL_AUTHENTICATION_ERROR"
    MODEL_PERMISSION_ERROR = "MODEL_PERMISSION_ERROR"
    MODEL_INVALID_REQUEST = "MODEL_INVALID_REQUEST"
    MODEL_RESPONSE_TOO_LARGE = "MODEL_RESPONSE_TOO_LARGE"
    MODEL_EMPTY_RESPONSE = "MODEL_EMPTY_RESPONSE"
    MODEL_INVALID_JSON = "MODEL_INVALID_JSON"
    MODEL_SCHEMA_INVALID = "MODEL_SCHEMA_INVALID"
    MODEL_BUSINESS_VALIDATION_FAILED = "MODEL_BUSINESS_VALIDATION_FAILED"
    MODEL_PROVIDER_UNAVAILABLE = "MODEL_PROVIDER_UNAVAILABLE"
    MODEL_FALLBACK_USED = "MODEL_FALLBACK_USED"
    MODEL_ALL_PROVIDERS_FAILED = "MODEL_ALL_PROVIDERS_FAILED"


class ModelAttemptOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    FALLBACK = "FALLBACK"
    SCOPE_BLOCKED = "SCOPE_BLOCKED"


class ProviderRole(StrEnum):
    PRIMARY = "PRIMARY"
    BACKUP = "BACKUP"
    TEMPLATE = "TEMPLATE"
    SCOPE_GUARD = "SCOPE_GUARD"


class FallbackType(StrEnum):
    TEMPLATE = "TEMPLATE"
