"""Controlled Agent contracts, partitions, and degraded modes."""

from enum import StrEnum


class AgentType(StrEnum):
    PROFILE_AGENT = "PROFILE_AGENT"
    PLAN_GENERATION = "PLAN_GENERATION"
    SESSION_DESIGNER = "SESSION_DESIGNER"
    SCHEDULE_AGENT = "SCHEDULE_AGENT"
    RECOVERY_AGENT = "RECOVERY_AGENT"


class ContextSectionName(StrEnum):
    SYSTEM_POLICY = "SYSTEM_POLICY"
    CURRENT_TASK = "CURRENT_TASK"
    PROFILE_SNAPSHOT = "PROFILE_SNAPSHOT"
    HARD_CONSTRAINTS = "HARD_CONSTRAINTS"
    SOFT_PREFERENCES = "SOFT_PREFERENCES"
    RELEVANT_CONFIRMED_MEMORIES = "RELEVANT_CONFIRMED_MEMORIES"
    RECENT_BEHAVIOR_SUMMARY = "RECENT_BEHAVIOR_SUMMARY"
    TOOL_EVIDENCE = "TOOL_EVIDENCE"
    OUTPUT_CONTRACT = "OUTPUT_CONTRACT"


class ContextDegradedMode(StrEnum):
    NONE = "NONE"
    NO_MEMORY = "NO_MEMORY"
