"""Controlled Memory classifications; medical facts are intentionally absent."""

from enum import StrEnum


class MemoryType(StrEnum):
    PREFERRED_LOCATION = "PREFERRED_LOCATION"
    PREFERRED_TIME_OF_DAY = "PREFERRED_TIME_OF_DAY"
    DISLIKED_ACTIVITY = "DISLIKED_ACTIVITY"
    PREFERRED_EQUIPMENT = "PREFERRED_EQUIPMENT"
    TRAINING_STYLE_PREFERENCE = "TRAINING_STYLE_PREFERENCE"


class MemoryStatus(StrEnum):
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    EXPIRED = "EXPIRED"
    DELETED = "DELETED"
    REJECTED = "REJECTED"


class MemorySource(StrEnum):
    USER_EXPLICIT = "USER_EXPLICIT"
    PROFILE_AGENT_CANDIDATE = "PROFILE_AGENT_CANDIDATE"
    BEHAVIOR_CANDIDATE = "BEHAVIOR_CANDIDATE"
    USER_EDIT = "USER_EDIT"


class MemoryEvidenceType(StrEnum):
    USER_CONFIRMATION = "USER_CONFIRMATION"
    PROFILE_DRAFT = "PROFILE_DRAFT"
    CHECK_IN_SUMMARY = "CHECK_IN_SUMMARY"
    MANUAL_EDIT = "MANUAL_EDIT"


class MemoryCandidateStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
