"""Enumerations shared by Tool Gateway ports and adapters."""

from enum import StrEnum


class ToolId(StrEnum):
    EXERCISE_CATALOG_SEARCH = "EXERCISE_CATALOG_SEARCH"
    SESSION_DURATION_CALCULATOR = "SESSION_DURATION_CALCULATOR"
    CALENDAR_FREE_BUSY = "CALENDAR_FREE_BUSY"
    RECOVERY_SPACING_VALIDATOR = "RECOVERY_SPACING_VALIDATOR"
    ICS_EXPORT = "ICS_EXPORT"
    CALENDAR_COMMIT = "CALENDAR_COMMIT"
    MEMORY_CANDIDATE_CREATE = "MEMORY_CANDIDATE_CREATE"


class ToolCaller(StrEnum):
    PROFILE_APPLICATION = "PROFILE_APPLICATION"
    PLAN_GENERATION_APPLICATION = "PLAN_GENERATION_APPLICATION"
    SESSION_DESIGN_APPLICATION = "SESSION_DESIGN_APPLICATION"
    SCHEDULE_APPLICATION = "SCHEDULE_APPLICATION"
    RECOVERY_APPLICATION = "RECOVERY_APPLICATION"
    MEMORY_COMMITTER = "MEMORY_COMMITTER"
    CALENDAR_EXECUTOR = "CALENDAR_EXECUTOR"
    ICS_EXPORT_SERVICE = "ICS_EXPORT_SERVICE"
    ORCHESTRATOR_WORKER = "ORCHESTRATOR_WORKER"
    INTERNAL_TEST = "INTERNAL_TEST"


class ToolSideEffectClass(StrEnum):
    PURE = "PURE"
    READ_ONLY = "READ_ONLY"
    INTERNAL_WRITE = "INTERNAL_WRITE"
    FILE_WRITE = "FILE_WRITE"
    EXTERNAL_WRITE = "EXTERNAL_WRITE"


class ToolInvocationStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    DEGRADED = "DEGRADED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    REJECTED = "REJECTED"


class ToolErrorCategory(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    PERMISSION = "PERMISSION"
    AUTHENTICATION = "AUTHENTICATION"
    AUTHORIZATION = "AUTHORIZATION"
    TIMEOUT = "TIMEOUT"
    CONNECTION = "CONNECTION"
    RATE_LIMIT = "RATE_LIMIT"
    UPSTREAM_5XX = "UPSTREAM_5XX"
    RESPONSE_TOO_LARGE = "RESPONSE_TOO_LARGE"
    RESPONSE_INVALID = "RESPONSE_INVALID"
    STALE_DATA = "STALE_DATA"
    BUSINESS_REJECTED = "BUSINESS_REJECTED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"
    BULKHEAD_REJECTED = "BULKHEAD_REJECTED"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ToolDegradationMode(StrEnum):
    NONE = "NONE"
    MANUAL_ONLY = "MANUAL_ONLY"
    NO_MEMORY = "NO_MEMORY"
    DETERMINISTIC_FALLBACK = "DETERMINISTIC_FALLBACK"
    READ_ONLY_ONLY = "READ_ONLY_ONLY"
    EXTERNAL_WRITE_DISABLED = "EXTERNAL_WRITE_DISABLED"
    STALE_DATA_REJECTED = "STALE_DATA_REJECTED"


class ToolAvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    DISABLED = "DISABLED"


class CircuitState(StrEnum):
    CLOSED = "CLOSED"
    OPEN = "OPEN"
    HALF_OPEN = "HALF_OPEN"
