"""Controlled classifications for behavior evidence and proposals."""

from enum import StrEnum


class BehaviorPatternType(StrEnum):
    REPEATED_SKIP_WEEKDAY = "REPEATED_SKIP_WEEKDAY"
    REPEATED_SKIP_TIME_OF_DAY = "REPEATED_SKIP_TIME_OF_DAY"
    REPEATED_COMPLETION_TIME_OF_DAY = "REPEATED_COMPLETION_TIME_OF_DAY"
    REPEATED_COMPLETION_LOCATION = "REPEATED_COMPLETION_LOCATION"
    REPEATED_SKIP_LOCATION = "REPEATED_SKIP_LOCATION"
    REPEATED_PARTIAL_COMPLETION = "REPEATED_PARTIAL_COMPLETION"
    REPEATED_HIGH_REPORTED_RPE = "REPEATED_HIGH_REPORTED_RPE"


class BehaviorConfidenceTier(StrEnum):
    THRESHOLD = "THRESHOLD"
    STRONG = "STRONG"


class BehaviorMemoryProposalStatus(StrEnum):
    PROPOSED = "PROPOSED"
    DISMISSED = "DISMISSED"
    EXPIRED = "EXPIRED"
