"""Controlled Recovery request, action, and lifecycle values."""

from enum import StrEnum


class RecoveryScopeStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class RecoveryRequestType(StrEnum):
    GENERAL_RECOVERY_REVIEW = "GENERAL_RECOVERY_REVIEW"
    RESCHEDULE_REQUEST = "RESCHEDULE_REQUEST"
    REDUCE_FUTURE_LOAD = "REDUCE_FUTURE_LOAD"
    REPLACE_FUTURE_SESSION = "REPLACE_FUTURE_SESSION"
    REMOVE_FUTURE_SESSION = "REMOVE_FUTURE_SESSION"
    NEXT_WEEK_REVIEW = "NEXT_WEEK_REVIEW"


class RecoveryActionType(StrEnum):
    KEEP_CURRENT_PLAN = "KEEP_CURRENT_PLAN"
    REQUEST_SESSION_RESCHEDULE = "REQUEST_SESSION_RESCHEDULE"
    REQUEST_SESSION_REDESIGN = "REQUEST_SESSION_REDESIGN"
    REMOVE_FUTURE_SESSION = "REMOVE_FUTURE_SESSION"
    NEXT_WEEK_FREQUENCY_REVIEW = "NEXT_WEEK_FREQUENCY_REVIEW"


class RecoveryRedesignGoal(StrEnum):
    LOWER_LOAD = "LOWER_LOAD"
    SHORTER_DURATION = "SHORTER_DURATION"
    LOW_IMPACT = "LOW_IMPACT"


class RecoveryDraftOutcome(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NO_CHANGE = "NO_CHANGE"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"


class RecoveryDraftSource(StrEnum):
    MODEL = "MODEL"
    DETERMINISTIC_FALLBACK = "DETERMINISTIC_FALLBACK"
    SCOPE_GUARD = "SCOPE_GUARD"


class RecoveryDraftStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    APPLIED = "APPLIED"
